return {
	"stevearc/conform.nvim",
	opts = {
		notify_on_error = false,
		format_on_save = {
			timeout_ms = 500,
			lsp_fallback = true,
		},
		formatters_by_ft = {
			c = { "clang-format" },
			["*"] = { "codespell" },
			css = { "prettier" },
			go = { "goimports", "gofumpt" },
			html = { "prettier" },
			javascript = { "prettier" },
			javascriptreact = { "prettier" },
			json = { "prettier" },
			lua = { "stylua" },
			markdown = { "prettier" },
			rust = { "rustfmt" },
			scss = { "prettier" },
			sh = { "shfmt" },
			["_"] = { "trim_whitespace" },
			typescript = { "prettier" },
			typescriptreact = { "prettier" },
			vue = { "prettier" },
			yaml = { "prettier" },
			svelte = { "prettier" },
		},
	},
}
